import "dotenv/config"; import mongoose from "mongoose"; import bcrypt from "bcryptjs";
import User from "../models/User.js"; import HotelType from "../models/HotelType.js"; import Destination from "../models/Destination.js"; import Amenity from "../models/Amenity.js"; import Hotel from "../models/Hotel.js"; import RoomType from "../models/RoomType.js"; import Room from "../models/Room.js"; import Inventory from "../models/Inventory.js"; import Coupon from "../models/Coupon.js"; import Booking from "../models/Booking.js"; import Payment from "../models/Payment.js"; import Review from "../models/Review.js"; import Wishlist from "../models/Wishlist.js"; import Notification from "../models/Notification.js"; import AuditLog from "../models/AuditLog.js"; import AIConversation from "../models/AIConversation.js"; import AIRecommendation from "../models/AIRecommendation.js"; import AIInsight from "../models/AIInsight.js";
const uri=process.env.MONGODB_URI;if(!uri)throw new Error("MONGODB_URI is missing in .env"); const days=(n)=>{const d=new Date();d.setDate(d.getDate()+n);d.setHours(0,0,0,0);return d}; const img=(id)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;
const seed=async()=>{await mongoose.connect(uri);console.log("MongoDB connected.");
for(const M of [Booking,Payment,Review,Wishlist,Notification,AuditLog,AIConversation,AIRecommendation,AIInsight,Inventory,Room,RoomType,Hotel,Coupon,Amenity,Destination,HotelType,User]) await M.deleteMany({});
const hash=await bcrypt.hash("123456",12); const users=await User.insertMany([
{fullName:"System Admin",email:"admin@123.com",passwordHash:hash,phone:"0900000001",role:"ADMIN",emailVerified:true},
{fullName:"Hotel Owner Demo",email:"owner@123.com",passwordHash:hash,phone:"0900000002",role:"HOTEL_OWNER",emailVerified:true},
{fullName:"Customer Demo",email:"customer@123.com",passwordHash:hash,phone:"0900000003",role:"CUSTOMER",emailVerified:true}
]); const admin=users[0],owner=users[1],customer=users[2];
const types=await HotelType.insertMany([
{name:"Khách sạn",slug:"hotel",description:"Lưu trú tiện nghi cho công tác và du lịch.",icon:"building-2",sortOrder:1,image:{url:img("photo-1566073771259-6a8506099945")}},
{name:"Resort",slug:"resort",description:"Không gian nghỉ dưỡng, hồ bơi và tiện ích cao cấp.",icon:"waves",sortOrder:2,image:{url:img("photo-1542314831-068cd1dbfeeb")}},
{name:"Villa",slug:"villa",description:"Không gian riêng tư phù hợp nhóm bạn và gia đình.",icon:"home",sortOrder:3,image:{url:img("photo-1584132967334-10e028bd69f7")}},
{name:"Căn hộ",slug:"apartment",description:"Căn hộ đầy đủ tiện nghi cho kỳ lưu trú dài ngày.",icon:"building",sortOrder:4,image:{url:img("photo-1522708323590-d24dbb6b0267")}},
{name:"Homestay",slug:"homestay",description:"Trải nghiệm địa phương gần gũi và độc đáo.",icon:"house",sortOrder:5,image:{url:img("photo-1564013799919-ab600027ffc6")}},
{name:"Boutique Hotel",slug:"boutique",description:"Thiết kế cá tính, quy mô vừa và trải nghiệm riêng.",icon:"sparkles",sortOrder:6,image:{url:img("photo-1564501049412-61c2a3083791")}}
]); const typeBy=Object.fromEntries(types.map(x=>[x.slug,x._id]));
const destinations=await Destination.insertMany([
{name:"Đà Nẵng",slug:"da-nang",shortDescription:"Biển đẹp, ẩm thực hấp dẫn và nhịp sống hiện đại.",description:"Điểm đến biển nổi bật miền Trung.",region:"Miền Trung",featured:true,sortOrder:1,image:{url:img("photo-1559592413-7cec4d0cae2b")}},
{name:"Đà Lạt",slug:"da-lat",shortDescription:"Khí hậu mát mẻ và những trải nghiệm lãng mạn.",region:"Tây Nguyên",featured:true,sortOrder:2,image:{url:img("photo-1557750255-c76072a7aad1")}},
{name:"Nha Trang",slug:"nha-trang",shortDescription:"Biển xanh, đảo đẹp và khu nghỉ dưỡng.",region:"Miền Trung",featured:true,sortOrder:3,image:{url:img("photo-1583417319070-4a69db38a482")}},
{name:"Phú Quốc",slug:"phu-quoc",shortDescription:"Đảo ngọc với biển xanh và nghỉ dưỡng.",region:"Miền Nam",featured:true,sortOrder:4,image:{url:img("photo-1518509562904-e7ef99cdcc86")}},
{name:"Hà Nội",slug:"ha-noi",shortDescription:"Văn hóa, phố cổ và ẩm thực đặc sắc.",region:"Miền Bắc",featured:true,sortOrder:5,image:{url:img("photo-1509030450996-dd1a26dda07a")}},
{name:"TP. Hồ Chí Minh",slug:"tp-ho-chi-minh",shortDescription:"Đô thị năng động và trung tâm kinh doanh.",region:"Miền Nam",featured:true,sortOrder:6,image:{url:img("photo-1523731407965-2430cd12f5e4")}},
{name:"Hội An",slug:"hoi-an",shortDescription:"Phố cổ, đèn lồng và văn hóa đặc trưng.",region:"Miền Trung",featured:true,sortOrder:7,image:{url:img("photo-1528127269322-539801943592")}},
{name:"Hạ Long",slug:"ha-long",shortDescription:"Vịnh biển và hành trình nghỉ dưỡng trên biển.",region:"Miền Bắc",featured:true,sortOrder:8,image:{url:img("photo-1548013146-72479768bada")}}
]); const destBy=Object.fromEntries(destinations.map(x=>[x.slug,x._id]));
const amenities=await Amenity.insertMany([
{name:"WiFi miễn phí",slug:"wifi",icon:"wifi",category:"BASIC"},{name:"Hồ bơi",slug:"swimming-pool",icon:"waves",category:"WELLNESS"},{name:"Bữa sáng",slug:"breakfast",icon:"utensils",category:"FOOD"},{name:"Phòng gym",slug:"gym",icon:"dumbbell",category:"WELLNESS"},{name:"Bãi đỗ xe",slug:"parking",icon:"car",category:"HOTEL"},{name:"Điều hòa",slug:"air-conditioning",icon:"snowflake",category:"ROOM"},{name:"Smart TV",slug:"smart-tv",icon:"tv",category:"ROOM"},{name:"Bồn tắm",slug:"bathtub",icon:"bath",category:"ROOM"}]); const amenityBy=Object.fromEntries(amenities.map(x=>[x.slug,x._id]));
const specs=[
["Da Nang Beach Hotel","da-nang-beach-hotel","Đà Nẵng","da-nang","RESORT",5,1250000,"photo-1566073771259-6a8506099945",4.8,124],["Saigon Riverside Hotel","saigon-riverside-hotel","TP. Hồ Chí Minh","tp-ho-chi-minh","HOTEL",5,1450000,"photo-1551882547-ff40c63fe5fa",4.7,98],["Hanoi Old Quarter Hotel","hanoi-old-quarter-hotel","Hà Nội","ha-noi","HOTEL",4,980000,"photo-1564501049412-61c2a3083791",4.6,86],["Nha Trang Ocean Resort","nha-trang-ocean-resort","Nha Trang","nha-trang","RESORT",5,1850000,"photo-1584132967334-10e028bd69f7",4.9,156],["Phu Quoc Paradise Resort","phu-quoc-paradise-resort","Phú Quốc","phu-quoc","RESORT",5,2150000,"photo-1542314831-068cd1dbfeeb",4.8,137],["Hoi An Ancient Boutique","hoi-an-ancient-boutique","Hội An","hoi-an","BOUTIQUE",4,1150000,"photo-1540541338287-41700207dee6",4.7,74],["Da Lat Pine Homestay","da-lat-pine-homestay","Đà Lạt","da-lat","HOMESTAY",3,720000,"photo-1564013799919-ab600027ffc6",4.5,62],["Ha Long Bay Villa","ha-long-bay-villa","Hạ Long","ha-long","VILLA",5,2400000,"photo-1601918774946-25832a4be0d6",4.9,41],["Central Saigon Apartment","central-saigon-apartment","TP. Hồ Chí Minh","tp-ho-chi-minh","APARTMENT",4,1100000,"photo-1522708323590-d24dbb6b0267",4.6,57],["Da Nang Boutique Stay","da-nang-boutique-stay","Đà Nẵng","da-nang","BOUTIQUE",4,1050000,"photo-1564501049412-61c2a3083791",4.6,39]];
const hotels=[];for(const [name,slug,city,dslug,t,stars,price,image,rating,reviews] of specs){hotels.push(await Hotel.create({ownerId:owner._id,hotelTypeId:typeBy[t.toLowerCase()],destinationId:destBy[dslug],name,slug,description:`${name} mang đến trải nghiệm lưu trú hiện đại tại ${city}, phù hợp cho kỳ nghỉ và chuyến công tác.`,starRating:stars,address:{addressLine:"Trung tâm thành phố",district:"Trung tâm",city,country:"Vietnam",postalCode:"700000"},location:{type:"Point",coordinates:[106.7+Math.random()/20,10.7+Math.random()/20]},images:[{url:img(image),isPrimary:true}],amenities:[amenityBy.wifi,amenityBy["swimming-pool"],amenityBy.breakfast,amenityBy["air-conditioning"],amenityBy.parking],policies:{checkInTime:"14:00",checkOutTime:"12:00",cancellationPolicy:"Miễn phí hủy trước 48 giờ.",childPolicy:"Trẻ em được chào đón.",petPolicy:"Vui lòng liên hệ trước."},contact:{phone:"028-1111-2222",email:`booking@${slug}.demo`},status:"APPROVED",isFeatured:reviews>=90,hotelType:t,averageRating:rating,reviewCount:reviews}));}
for(const d of destinations) await Destination.updateOne({_id:d._id},{$set:{hotelCount:hotels.filter(h=>String(h.destinationId)===String(d._id)).length}});
const roomTypes=[];for(const [i,h] of hotels.entries()){const r=await RoomType.create({hotelId:h._id,name:"Deluxe King",slug:"deluxe-king",description:"Phòng rộng, giường King và tiện nghi hiện đại.",capacity:{adults:2,children:1,total:3},bedType:"1 King Bed",size:32,basePrice:specs[i][6],images:[{url:img(specs[i][7])}],amenities:[amenityBy.wifi,amenityBy["air-conditioning"],amenityBy["smart-tv"]],totalRooms:10,status:"ACTIVE"});roomTypes.push(r);await RoomType.create({hotelId:h._id,name:"Family Suite",slug:"family-suite",description:"Phòng gia đình với không gian rộng.",capacity:{adults:3,children:2,total:5},bedType:"1 King + 1 Sofa Bed",size:48,basePrice:specs[i][6]*1.45,images:[{url:img(specs[i][7])}],amenities:[amenityBy.wifi,amenityBy["air-conditioning"],amenityBy["bathtub"]],totalRooms:6,status:"ACTIVE"});}
const rooms=[];for(const rt of await RoomType.find({})){for(let n=1;n<=rt.totalRooms;n++)rooms.push({hotelId:rt.hotelId,roomTypeId:rt._id,roomNumber:`${String(rt._id).slice(-3)}-${String(n).padStart(3,"0")}`,floor:1,status:"AVAILABLE"});} await Room.insertMany(rooms);
const inv=[];for(const rt of await RoomType.find({})){for(let d=0;d<120;d++){const date=days(d);inv.push({hotelId:rt.hotelId,roomTypeId:rt._id,date,totalRooms:rt.totalRooms,availableRooms:rt.totalRooms,price:rt.basePrice,blockedRooms:0});}} await Inventory.insertMany(inv,{ordered:false});
const now=new Date();const coupons=await Coupon.insertMany([
{code:"WELCOME10",title:"Giảm 10% cho khách mới",shortDescription:"Ưu đãi dành cho lần đặt phòng đầu tiên.",badge:"-10%",discountType:"PERCENTAGE",discountValue:10,maxDiscount:300000,minBookingAmount:500000,usageLimit:1000,startDate:days(-30),endDate:days(180),featured:true,description:"Áp dụng cho đơn đủ điều kiện.",terms:["Đơn tối thiểu 500.000đ","Mỗi khách hàng sử dụng một lần"],status:"ACTIVE"},
{code:"SUMMER20",title:"Kỳ nghỉ tiết kiệm",shortDescription:"Giảm 20% cho kỳ nghỉ mùa hè.",badge:"-20%",discountType:"PERCENTAGE",discountValue:20,maxDiscount:600000,minBookingAmount:1500000,usageLimit:500,startDate:days(-10),endDate:days(90),featured:true,description:"Áp dụng tại các khách sạn tham gia.",terms:["Đơn tối thiểu 1.500.000đ"],status:"ACTIVE"},
{code:"WEEKEND15",title:"Cuối tuần thư giãn",shortDescription:"Giảm 15% cho những chuyến đi cuối tuần.",badge:"-15%",discountType:"PERCENTAGE",discountValue:15,maxDiscount:400000,minBookingAmount:1000000,usageLimit:500,startDate:days(-5),endDate:days(120),featured:false,terms:["Áp dụng cho đơn từ 1.000.000đ"],status:"ACTIVE"},
{code:"DANANG25",title:"Đà Nẵng biển xanh",shortDescription:"Ưu đãi đến 25% tại Đà Nẵng.",badge:"-25%",discountType:"PERCENTAGE",discountValue:25,maxDiscount:800000,minBookingAmount:2000000,usageLimit:200,startDate:days(-3),endDate:days(60),featured:true,applicableHotels:hotels.filter(h=>String(h.destinationId)===String(destBy["da-nang"])).map(h=>h._id),terms:["Áp dụng tại khách sạn tham gia"],status:"ACTIVE"}
]);
const demoRt=roomTypes[0],demoHotel=hotels[0]; const ci=days(2),co=days(4);for(let d=new Date(ci);d<co;d.setDate(d.getDate()+1))await Inventory.updateOne({roomTypeId:demoRt._id,date:new Date(d)},{$inc:{availableRooms:-1}});
const booking=await Booking.create({bookingCode:"HTL-DEMO-0001",userId:customer._id,hotelId:demoHotel._id,roomTypeId:demoRt._id,checkIn:ci,checkOut:co,guests:{adults:2,children:0},rooms:1,guestInfo:{fullName:customer.fullName,email:customer.email,phone:customer.phone,note:"Demo seed booking"},pricePerNight:demoRt.basePrice,nights:2,subtotal:demoRt.basePrice*2,discount:0,totalAmount:demoRt.basePrice*2,status:"CONFIRMED",paymentStatus:"PAID"});await Payment.create({bookingId:booking._id,userId:customer._id,amount:booking.totalAmount,method:"MOCK",status:"SUCCEEDED",paidAt:new Date()});await Review.create({bookingId:booking._id,userId:customer._id,hotelId:demoHotel._id,rating:5,title:"Kỳ nghỉ tuyệt vời",comment:"Phòng sạch, vị trí thuận tiện và dịch vụ tốt.",status:"PUBLISHED"});await Wishlist.create({userId:customer._id,hotelId:demoHotel._id});await Notification.insertMany([{userId:customer._id,type:"BOOKING",title:"Chào mừng bạn đến HOTELAI",message:"Tài khoản demo đã sẵn sàng để trải nghiệm hệ thống."},{userId:owner._id,type:"SYSTEM",title:"Chào mừng Hotel Owner",message:"Bạn có thể quản lý khách sạn từ dashboard."}]);await AuditLog.create({actorId:admin._id,action:"SEED_DATABASE",entity:"System",metadata:{hotels:hotels.length,roomTypes:(await RoomType.countDocuments()),inventory:await Inventory.countDocuments()}});await AIConversation.create({userId:customer._id,title:"Tư vấn chuyến đi Đà Nẵng",messages:[{role:"user",content:"Gợi ý khách sạn ở Đà Nẵng"},{role:"assistant",content:"Bạn có thể thử các khách sạn nổi bật gần biển Mỹ Khê."}]});await AIRecommendation.create({userId:customer._id,hotelIds:hotels.slice(0,3).map(h=>h._id),reason:"Dựa trên điểm đến và mức đánh giá",source:"RULE_BASED",score:0.92});await AIInsight.create({hotelId:demoHotel._id,period:"seed-demo",occupancyRate:68,revenue:booking.totalAmount,averageBookingValue:booking.totalAmount,insight:"Demo insight cho dashboard AI.",recommendations:["Theo dõi giá cuối tuần","Tăng ưu đãi cho ngày thấp điểm"]});
const finalRoomTypeCount=await RoomType.countDocuments(); const finalInventoryCount=await Inventory.countDocuments(); await mongoose.disconnect();console.log("\nSEED COMPLETE");console.log("DB: hotel_booking");console.log("Login demo: admin@123.com / owner@123.com / customer@123.com - password 123456");console.log("Hotels:",hotels.length,"RoomTypes:",finalRoomTypeCount,"Inventory:",finalInventoryCount);};seed().catch(e=>{console.error("SEED FAILED",e);process.exit(1)});
